services:
  _defaults:
    autowire: true
    autoconfigure: true

  WebEtDesign\MediaBundle\:
    resource: '../../*'
    exclude:
      - '../../DependencyInjection'
      - '../../Entity'
      - '../../Twig'

  WebEtDesign\MediaBundle\Controller\:
    resource: '../../Controller'
    tags: [ 'controller.service_arguments' ]

  WebEtDesign\MediaBundle\Vich\WDMediaDirectoryNamer:
    public: true

  WebEtDesign\MediaBundle\Listener\OptimizerListener:
    tags:
      - { name: kernel.event_listener, event: vich_uploader.post_upload }

  WebEtDesign\MediaBundle\Form\Type\CategoryFilterType:
    autowire: true
    autoconfigure: true
    public: true
    tags:
      - { name: sonata.admin.filter.type }
